<a href="https://colab.research.google.com/github/mantoan-thi/Deep_Learning_with_Python/blob/main/Multiclass_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np
import math
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from sklearn.metrics import confusion_matrix
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [4]:
class classificador_multiclasses():
  def __init__(self,base,classe,qtde_valores_previstos):
    self.previsores = base.drop(columns=[classe]).values
    self.classe = base[classe].values
    self.input_inicial = self.previsores.shape[1]
    self.neuron = math.ceil((self.previsores.shape[1]+qtde_valores_previstos)/2) 
    self.qtde_valores_previstos = qtde_valores_previstos
    
  def criar_rede(self):
    # Processando
    labelencoder = LabelEncoder()
    self.classe = labelencoder.fit_transform(self.classe)
    self.classe_dummy = np_utils.to_categorical(self.classe)
    self.previsore_train,self.previsores_test,self.classe_train,self.classe_test = train_test_split(self.previsores,self.classe_dummy,test_size=0.25)

    # Modelo
    self.classificador = Sequential()
    self.classificador.add(Dense(units=self.neuron,activation='relu',input_dim = self.input_inicial))
    self.classificador.add(Dense(units=self.neuron,activation='relu'))
    # Camada de saída
    self.classificador.add(Dense(units=self.qtde_valores_previstos,activation='softmax',))
    # Compilação da rede neural
    self.classificador.compile(optimizer = 'adam',loss='categorical_crossentropy',metrics=['categorical_accuracy'])
    
    self.classificador.fit(self.previsore_train,self.classe_train,batch_size=10,epochs=1000)

    # Avaliação
    self.resultado = self.classificador.evaluate(self.previsores_test,self.classe_test)
    self.previsoes = self.classificador.predict(self.previsores_test)
    self.previsoes = (self.previsoes > 0.5)
    self.classe_test2 = [np.argmax(t) for t in self.classe_test]
    self.previsores2 = [np.argmax(t) for t in self.previsoes]
    self.matrix = confusion_matrix(self.previsores2,self.classe_test2)
    return self.previsores_test,self.resultado,self.matrix 

  #def Built_Model_Cross(self):
  #  self.classificador2 = KerasClassifier(build_fn=self.criar_rede,epochs=1000, batch_size=10)
  #  self.resultados = cross_val_score(estimator=self.classificador2,X=self.previsores,y=self.classe,cv=10,scoring='accuracy')
  #  self.media = self.resultados.mean()
  #  self.desvio = self.resultados.std()
  #  return self.media,self.desvio,self.resultados




    # Prevendo 1 valor
  def predict_vlr(self,valores):
      self.valor_previsto = self.classificador.predict(valores)
      return np.argmax(self.valor_previsto)



In [5]:
classe = 'class'
base = pd.read_csv('/content/iris.csv')

In [6]:
model = classificador_multiclasses(base,classe,3)

In [20]:
# Criando a rede
previsores_test,resultado,matrix  = model.criar_rede()

Epoch 1/1000
12/12 [==============================] - 0s 2ms/step - loss: 1.1638 - categorical_accuracy: 0.3304
Epoch 2/1000
12/12 [==============================] - 0s 2ms/step - loss: 1.1464 - categorical_accuracy: 0.3304
Epoch 3/1000
12/12 [==============================] - 0s 2ms/step - loss: 1.1330 - categorical_accuracy: 0.3304
Epoch 4/1000
12/12 [==============================] - 0s 3ms/step - loss: 1.1224 - categorical_accuracy: 0.3304
Epoch 5/1000
12/12 [==============================] - 0s 2ms/step - loss: 1.1138 - categorical_accuracy: 0.3304
Epoch 6/1000
12/12 [==============================] - 0s 2ms/step - loss: 1.1051 - categorical_accuracy: 0.3304
Epoch 7/1000
12/12 [==============================] - 0s 2ms/step - loss: 1.0966 - categorical_accuracy: 0.3304
Epoch 8/1000
12/12 [==============================] - 0s 2ms/step - loss: 1.0901 - categorical_accuracy: 0.3304
Epoch 9/1000
12/12 [==============================] - 0s 2ms/step - loss: 1.0849 - categorical_accuracy:

In [21]:
print('Acuracidade do modelo: {:.0%}'.format(resultado[1]))

Acuracidade do modelo: 95%


In [22]:
print('Matrix de Confusão: \n',matrix)

Matrix de Confusão: 
 [[13  0  0]
 [ 0 10  0]
 [ 0  2 13]]


In [23]:
previsores_test[:1]

array([[5.1, 3.3, 1.7, 0.5]])

In [24]:
# iris setosa = 0
# iris virginica = 1
# iris versicolor = 2


# Prevendo apenas 1 valor
model.predict_vlr(previsores_test[:1])

0